# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06727c4a4d41d075f6d80d806064c7a5419fece1949d43f6dd5320e56fed69b7d42689fb88b0ce272de5762cd6063d2b8276e21f085decc1db64870af78413ca

test:
  secret_key_base: dfb0fb7d628bfe467d1ca6632d92595bdffb387010c52a2ca604aec15fbf70de8d8ff880d0f4b79c7500a9683e21c9bb4e79221e2fcc540ab244609f2bd0e4d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
